### ISSUE TITLE
Suggestion: Use term "Workers" for the "Users"

### ISSUE THREAD

**Issue by ChrisChasm** [ChasmSolutions/disciple-tools#106]
<img width="353" alt="screen shot 2017-07-26 at 1 35 53 pm" src="https://user-images.githubusercontent.com/7318348/28639993-787d91f2-7207-11e7-9a4f-b4dd2631a037.png">
I suggest we use "Workers" for the section of DT that houses user accounts. This can house the multipliers, marketers, dispatchers, strategists ... i.e. all the workers of the project.

Even for those contacts that become a part of the project will get a user account to handle contacts and would also be come a "worker" in the project.

**Comment by himayrunner** [comment]
I agree with this. I think that (at least in our context) everyone knows we are 'workers'. Users could be us or it could be the seekers we are serving online.

**Comment by ChrisChasm** [comment]
Agreed on by everyone.
