### ISSUE TITLE
Sharing: Get all contacts shared with me.

### ISSUE THREAD

**Issue by corsacca** [ChasmSolutions/disciple-tools#135]
Right now i can get a list of users the contact is shared with. 
Is there a way to get all the contacts that are shared with a user?
We are not storing the post type in the shared table, so the current solution is to get all posts shared with a user, then get each post and only keep those that are contacts.

**Comment by ChrisChasm** [comment]
Nope. That function is not written. And yes, I clearly wasn't thinking widely about having sharing work with different post types. 

- [ ] We could add a column for post type info
- [ ] We could use the `meta` column and make post type on piece of metadata. (The original thought with the meta column, was to include other data like ('accepted share', 'don't notify', etc)

**Comment by corsacca** [comment]
Thinking about it. The post_type won't change for an ID, so it is just storing information to make life easy.
Maybe we can modify the sql query to check the post type. A join?

**Comment by ChrisChasm** [comment]
A join would be an easy solution and you wouldn't have to maintain redundant information.

**Comment by corsacca** [comment]
Implemented with #150
