### ISSUE TITLE
Error on contact details page

### ISSUE THREAD

**Issue by ahillbilly** [ChasmSolutions/disciple-tools#138]
Contact List page was stuck "Loading", so I went to group list and it loaded.  I selected a contact and opened the contact details page and got the following 3 errors.

Notice: Undefined offset: 1 in /var/www/html/wp-content/plugins/disciple-tools/dt-contacts/contacts-post-type.php on line 1099

Notice: Undefined property: WP_Error::$term_id in /var/www/html/wp-content/plugins/disciple-tools/dt-contacts/contacts-post-type.php on line 1110

Notice: Undefined property: WP_Error::$name in /var/www/html/wp-content/plugins/disciple-tools/dt-contacts/contacts-post-typ

![testy_tester_002_ _staging_disciple_tools](https://user-images.githubusercontent.com/25323324/30381358-1a37cc08-9894-11e7-9ea9-e188118e4eec.jpg)

**Comment by corsacca** [comment]
This error is due to a contact being assigned to dispatch instead of a user.
@ChrisChasm @ahillbilly I think we decided that a contact can only be assigned to a user. So dispatch and groups should be remove from the options in the admin interface.

**Comment by corsacca** [comment]
some code area as https://github.com/ChasmSolutions/disciple-tools/issues/137
